#!/usr/bin/env python3
"""Batch 12 rewrite: United States, China, India, Japan, Brazil, Indonesia, Nigeria, Pakistan, Bangladesh, Russia, Saudi Arabia, UAE, Singapore, Taiwan, Israel, Ireland, Netherlands, Sweden, Sri Lanka"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import the template engine from batch2
from batch2_rewrite import gen_article, AUDIENCES, ARTICLES_DIR, AUDIENCE_TITLES

COUNTRIES = {
    "us": {
        "name": "United States", "slug": "us-us", "population": "338 million",
        "gdp_per_capita": "$85,810", "gdp_per_capita_ppp": "$85,810", "gdp_growth": "2.7% (2024)",
        "currency": "USD", "avg_monthly_salary": "$6,150 (~$6,150 USD)",
        "avg_salary_usd": "$6,150", "minimum_wage": "$7.25/hour (federal; state varies $10.45-$16.28)",
        "it_salary_range": "$90,000-160,000/year; senior $150,000-250,000+",
        "manufacturing_salary": "$55,000-75,000/year",
        "unemployment": "4.0%",
        "ai_adoption": "Highest globally; Silicon Valley, AI startup ecosystem, major tech giants (OpenAI, Google, Meta, Microsoft) leading development; $26B+ VC funding in AI 2024",
        "internet_penetration": "92%", "literacy_rate": "99%",
        "stem_graduates": "~600,000 annually",
        "labor_force": "167 million",
        "key_industries": "Technology, finance, healthcare, manufacturing, energy, telecommunications, entertainment, aerospace, pharmaceuticals, defense",
        "ai_risk_high": "Administrative services, call centers, financial back-office, data entry, basic customer service, bookkeeping",
        "ai_risk_medium": "Banking operations, manufacturing, logistics, retail, insurance, paralegal services, accounting",
        "ai_risk_low": "Healthcare (medical care), education, skilled trades, R&D, creative industries, engineering, senior legal services",
        "key_challenges": "Skills gap in tech despite high education, income inequality widening, geographic tech concentration, healthcare AI integration complexity, workforce transition demands",
        "references": [
            ("World Bank - USA Data", "https://data.worldbank.org/country/united-states"),
            ("Bureau of Labor Statistics", "https://www.bls.gov/"),
            ("Trading Economics - USA", "https://tradingeconomics.com/united-states/indicators"),
            ("US Census Bureau - Economic Data", "https://www.census.gov/topics/economy/economic-census.html"),
            ("OECD - USA Economic Survey", "https://www.oecd.org/en/topics/sub-issues/economic-surveys-united-states.html"),
            ("IMF - World Economic Outlook USA", "https://www.imf.org/en/Countries/USA"),
        ]
    },
    "china": {
        "name": "China", "slug": "china-china", "population": "1.426 billion",
        "gdp_per_capita": "$13,121", "gdp_per_capita_ppp": "$24,800", "gdp_growth": "5.0% (2024)",
        "currency": "CNY", "avg_monthly_salary": "CNY 8,900 (~$1,290 USD; urban avg)",
        "avg_salary_usd": "$1,290", "minimum_wage": "CNY 1,980-3,000/month (varies by province; 2024)",
        "it_salary_range": "CNY 15,000-40,000/month; senior CNY 50,000-100,000+",
        "manufacturing_salary": "CNY 6,000-12,000/month (~$870-1,740 USD)",
        "unemployment": "5.1% (2024)",
        "ai_adoption": "World leader in AI deployment; generative AI, face recognition, autonomous vehicles; government-led digital transformation; Alibaba, Tencent, Baidu as global players",
        "internet_penetration": "74%", "literacy_rate": "97%",
        "stem_graduates": "~1.2 million annually (highest globally)",
        "labor_force": "770 million",
        "key_industries": "Manufacturing (electronics, textiles, automobiles), IT, telecommunications, finance, e-commerce, renewable energy, pharmaceuticals, steel",
        "ai_risk_high": "Manufacturing assembly, call centers, basic data processing, textile production, administrative services",
        "ai_risk_medium": "Automotive manufacturing, banking, logistics, e-commerce operations, retail",
        "ai_risk_low": "Healthcare, education, engineering, R&D, renewable energy, skilled trades, creative industries",
        "key_challenges": "Aging population (labor force declining), youth unemployment pressure, real estate crisis, geopolitical tech restrictions (US sanctions), manufacturing labor cost pressure",
        "references": [
            ("World Bank - China Data", "https://data.worldbank.org/country/china"),
            ("National Bureau of Statistics China", "https://www.stats.gov.cn/english/"),
            ("Trading Economics - China", "https://tradingeconomics.com/china/indicators"),
            ("China-briefing.com Economic Analysis", "https://www.china-briefing.com/news/"),
            ("CEIC - China Economic Data", "https://www.ceicdata.com/en/countries/china"),
        ]
    },
    "india": {
        "name": "India", "slug": "india-india", "population": "1.428 billion",
        "gdp_per_capita": "$2,777", "gdp_per_capita_ppp": "$13,500", "gdp_growth": "6.2% (2024)",
        "currency": "INR", "avg_monthly_salary": "INR 28,000-35,000 (~$330-420 USD)",
        "avg_salary_usd": "$330-420", "minimum_wage": "INR 300-700/day (varies by state; 2024)",
        "it_salary_range": "INR 400,000-800,000/year (~$4,800-9,600 USD); senior INR 1M-3M+",
        "manufacturing_salary": "INR 200,000-400,000/year (~$2,400-4,800 USD)",
        "unemployment": "3.2% (2024, official; underemployment significant)",
        "ai_adoption": "Rapid growth; IT services dominance (Infosys, TCS, Wipro); AI talent pool for global firms; government AI vision; emerging ML/AI startups",
        "internet_penetration": "45%", "literacy_rate": "74%",
        "stem_graduates": "~2.5 million annually",
        "labor_force": "530 million",
        "key_industries": "IT services, manufacturing, pharmaceuticals, textiles, agriculture, oil & gas, telecommunications, media, mining, construction",
        "ai_risk_high": "Call centers (2M+ BPO workers), data entry, basic administrative services, textile production, retail",
        "ai_risk_medium": "IT-BPO services, banking, manufacturing, logistics, pharmaceutical admin",
        "ai_risk_low": "Engineering services (valued for complex work), healthcare, education, agriculture, construction, creative industries",
        "key_challenges": "Skill-wage mismatch despite STEM talent, agricultural labor transition, informal employment dominance (90% labor force), rural-urban divide, infrastructure gaps",
        "references": [
            ("World Bank - India Data", "https://data.worldbank.org/country/india"),
            ("Ministry of Statistics India", "https://mospi.gov.in/"),
            ("Trading Economics - India", "https://tradingeconomics.com/india/indicators"),
            ("CEIC - India Indicators", "https://www.ceicdata.com/en/countries/india"),
            ("RBI - Reserve Bank of India", "https://www.rbi.org.in/"),
        ]
    },
    "japan": {
        "name": "Japan", "slug": "japan-japan", "population": "125 million",
        "gdp_per_capita": "$32,443", "gdp_per_capita_ppp": "$43,500", "gdp_growth": "1.2% (2024)",
        "currency": "JPY", "avg_monthly_salary": "JPY 471,000 (~$3,140 USD)",
        "avg_salary_usd": "$3,140", "minimum_wage": "¥1,307-1,112/hour (varies by prefecture; 2025)",
        "it_salary_range": "¥5.5M-8M/year (~$36,700-53,300 USD); senior ¥10M-18M+",
        "manufacturing_salary": "¥3.5M-5M/year (~$23,300-33,300 USD)",
        "unemployment": "2.4%",
        "ai_adoption": "Strong in robotics, manufacturing automation; tech giants (Sony, Toyota, NEC) investing in AI; weak in generative AI vs US/China",
        "internet_penetration": "99%", "literacy_rate": "99%",
        "stem_graduates": "~200,000 annually",
        "labor_force": "75 million",
        "key_industries": "Automotive, electronics, machinery, chemicals, pharmaceuticals, semiconductors, robotics, steel, financial services",
        "ai_risk_high": "Manufacturing assembly, administrative services, data processing, basic customer service, retail checkout",
        "ai_risk_medium": "Automotive manufacturing, banking, insurance, logistics, electronics assembly",
        "ai_risk_low": "Healthcare, education, skilled manufacturing, engineering, robotics development, creative industries, hospitality",
        "key_challenges": "Severe demographic crisis (declining workforce, aging population 29% over 65), low immigration, stagnant productivity, generational wage gaps, rural depopulation",
        "references": [
            ("World Bank - Japan Data", "https://data.worldbank.org/country/japan"),
            ("Statistics Bureau of Japan", "https://www.stat.go.jp/english/"),
            ("Trading Economics - Japan", "https://tradingeconomics.com/japan/indicators"),
            ("CEIC - Japan Economic Data", "https://www.ceicdata.com/en/countries/japan"),
            ("OECD - Japan Economic Survey", "https://www.oecd.org/en/topics/sub-issues/economic-surveys-japan.html"),
        ]
    },
    "brazil": {
        "name": "Brazil", "slug": "brazil-brazil", "population": "212 million",
        "gdp_per_capita": "$9,564", "gdp_per_capita_ppp": "$19,800", "gdp_growth": "2.1% (2024)",
        "currency": "BRL", "avg_monthly_salary": "BRL 3,294 (~$580 USD)",
        "avg_salary_usd": "$580", "minimum_wage": "BRL 1,412/month (2025)",
        "it_salary_range": "BRL 6,000-15,000/month; senior BRL 20,000-40,000+",
        "manufacturing_salary": "BRL 2,500-5,000/month (~$440-880 USD)",
        "unemployment": "6.8%",
        "ai_adoption": "Growing; government AI policy; tech hubs in São Paulo, Rio; Microsoft, Google investing locally",
        "internet_penetration": "88%", "literacy_rate": "93%",
        "stem_graduates": "~350,000 annually",
        "labor_force": "112 million",
        "key_industries": "Agriculture (coffee, sugar, soybeans), mining, oil & gas, automotive, textiles, finance, telecommunications, machinery",
        "ai_risk_high": "Telemarketing/call centers, agricultural administration, textile assembly, financial data entry, retail",
        "ai_risk_medium": "Automotive manufacturing, banking, mining operations, logistics, insurance",
        "ai_risk_low": "Healthcare, education, agriculture operations, skilled trades, creative industries, oil industry engineering",
        "key_challenges": "Income inequality (Gini 0.54), inflation pressures, currency volatility, tax burden, agricultural commodity dependence, infrastructure gaps",
        "references": [
            ("World Bank - Brazil Data", "https://data.worldbank.org/country/brazil"),
            ("IBGE - Brazilian Statistics", "https://www.ibge.gov.br/"),
            ("Trading Economics - Brazil", "https://tradingeconomics.com/brazil/indicators"),
            ("Central Bank of Brazil", "https://www.bcb.gov.br/"),
            ("OECD - Brazil Economic Survey", "https://www.oecd.org/en/topics/sub-issues/economic-surveys-brazil.html"),
        ]
    },
    "indonesia": {
        "name": "Indonesia", "slug": "indonesia-indonesia", "population": "277 million",
        "gdp_per_capita": "$4,960", "gdp_per_capita_ppp": "$16,200", "gdp_growth": "5.0% (2024)",
        "currency": "IDR", "avg_monthly_salary": "IDR 4,500,000-6,500,000 (~$280-405 USD)",
        "avg_salary_usd": "$280-405", "minimum_wage": "IDR 5.15M/month (Jakarta; varies by region; 2024)",
        "it_salary_range": "IDR 8M-20M/month; senior IDR 30M-60M+",
        "manufacturing_salary": "IDR 3M-7M/month (~$187-435 USD)",
        "unemployment": "5.5%",
        "ai_adoption": "Growing; fintech boom; Gojek, Grab, Tokopedia as tech hubs; government digital transformation",
        "internet_penetration": "68%", "literacy_rate": "97%",
        "stem_graduates": "~180,000 annually",
        "labor_force": "140 million",
        "key_industries": "Palm oil, mining, oil & gas, textiles, automotive, electronics, agriculture, telecommunications, financial services",
        "ai_risk_high": "Palm oil processing, textile manufacturing assembly, call centers, agricultural admin, retail",
        "ai_risk_medium": "Automotive manufacturing, banking, mining operations, logistics, e-commerce",
        "ai_risk_low": "Healthcare, education, skilled trades, oil industry engineering, creative industries, agriculture services",
        "key_challenges": "Informal economy dominance (60%+ of workforce), infrastructure gaps, geographic dispersion challenges, commodity price dependency, education-skills gap",
        "references": [
            ("World Bank - Indonesia Data", "https://data.worldbank.org/country/indonesia"),
            ("BPS - Statistics Indonesia", "https://www.bps.go.id/en/"),
            ("Trading Economics - Indonesia", "https://tradingeconomics.com/indonesia/indicators"),
            ("CEIC - Indonesia Data", "https://www.ceicdata.com/en/countries/indonesia"),
            ("ADB - Indonesia Country Profile", "https://www.adb.org/countries/indonesia/main"),
        ]
    },
    "nigeria": {
        "name": "Nigeria", "slug": "nigeria-nigeria", "population": "223 million",
        "gdp_per_capita": "$2,447", "gdp_per_capita_ppp": "$12,000", "gdp_growth": "3.5% (2024)",
        "currency": "NGN", "avg_monthly_salary": "NGN 250,000-350,000 (~$155-220 USD)",
        "avg_salary_usd": "$155-220", "minimum_wage": "NGN 70,000/month (2024)",
        "it_salary_range": "NGN 400,000-1.5M/month; senior NGN 2M-5M+",
        "manufacturing_salary": "NGN 150,000-300,000/month (~$90-185 USD)",
        "unemployment": "3.5% (official; underemployment 40%+)",
        "ai_adoption": "Emerging; Lagos tech hub; fintech innovation (Flutterwave, Paystack); government tech agenda",
        "internet_penetration": "45%", "literacy_rate": "66%",
        "stem_graduates": "~200,000 annually",
        "labor_force": "90 million",
        "key_industries": "Oil & gas, agriculture, telecommunications, financial services, textiles, food processing, mining, retail, entertainment (Nollywood)",
        "ai_risk_high": "Oil sector admin, call centers, textile manufacturing, agricultural processing, retail",
        "ai_risk_medium": "Banking, telecommunications, logistics, oil operations, fintech services",
        "ai_risk_low": "Healthcare, education, skilled trades, agriculture, creative industries (entertainment), oil industry engineering",
        "key_challenges": "Oil dependency (90% exports), infrastructure gaps (power shortages), poverty (40%+ below poverty line), education quality, insecurity in north, youth unemployment",
        "references": [
            ("World Bank - Nigeria Data", "https://data.worldbank.org/country/nigeria"),
            ("National Bureau of Statistics Nigeria", "https://nigerianstat.gov.ng/"),
            ("Trading Economics - Nigeria", "https://tradingeconomics.com/nigeria/indicators"),
            ("Central Bank of Nigeria", "https://www.cbn.gov.ng/"),
            ("AFDB - Nigeria Country Profile", "https://www.afdb.org/en/countries/west-africa/nigeria"),
        ]
    },
    "pakistan": {
        "name": "Pakistan", "slug": "pakistan-pakistan", "population": "240 million",
        "gdp_per_capita": "$1,707", "gdp_per_capita_ppp": "$9,100", "gdp_growth": "2.4% (2024)",
        "currency": "PKR", "avg_monthly_salary": "PKR 82,100 (~$294 USD)",
        "avg_salary_usd": "$294", "minimum_wage": "PKR 37,000/month (federal; varies by province; 2024)",
        "it_salary_range": "PKR 700,000-1.5M/year (~$2,500-5,400 USD); senior PKR 2M-5M+",
        "manufacturing_salary": "PKR 400,000-800,000/year (~$1,400-2,900 USD)",
        "unemployment": "5.2%",
        "ai_adoption": "Growing; Karachi tech hub; software outsourcing industry $2.5B; Daraz, Zameen as local tech champions",
        "internet_penetration": "48%", "literacy_rate": "59%",
        "stem_graduates": "~250,000 annually",
        "labor_force": "130 million",
        "key_industries": "Textiles (25% of exports), agriculture, oil & gas, construction, automotive, telecommunications, food processing, software services",
        "ai_risk_high": "Textile manufacturing, call centers, agricultural processing, basic admin, retail",
        "ai_risk_medium": "Automotive manufacturing, banking, oil sector, software services admin, logistics",
        "ai_risk_low": "Healthcare, education, skilled trades, agriculture, software engineering (valued globally), oil engineering",
        "key_challenges": "Power crisis, inflation (16%+), security concerns, infrastructure gaps, education quality, political instability, remittance dependency ($32B/year)",
        "references": [
            ("World Bank - Pakistan Data", "https://data.worldbank.org/country/pakistan"),
            ("PBS - Pakistan Statistics", "https://www.pbs.gov.pk/"),
            ("Trading Economics - Pakistan", "https://tradingeconomics.com/pakistan/indicators"),
            ("State Bank of Pakistan", "https://www.sbp.org.pk/"),
            ("ADB - Pakistan Country Profile", "https://www.adb.org/countries/pakistan/main"),
        ]
    },
    "bangladesh": {
        "name": "Bangladesh", "slug": "bangladesh-bangladesh", "population": "173 million",
        "gdp_per_capita": "$2,734", "gdp_per_capita_ppp": "$12,500", "gdp_growth": "5.9% (2024)",
        "currency": "BDT", "avg_monthly_salary": "BDT 22,000-28,000 (~$210-265 USD)",
        "avg_salary_usd": "$210-265", "minimum_wage": "BDT 12,500/month (2024, garment workers have higher minimum)",
        "it_salary_range": "BDT 400,000-1M/year (~$3,800-9,500 USD); senior BDT 1.5M-3M+",
        "manufacturing_salary": "BDT 150,000-300,000/year (~$1,400-2,900 USD)",
        "unemployment": "5.4%",
        "ai_adoption": "Emerging; government Digital Bangladesh vision; fintech growth; startups in Dhaka",
        "internet_penetration": "50%", "literacy_rate": "75%",
        "stem_graduates": "~200,000 annually",
        "labor_force": "65 million",
        "key_industries": "Garments (80% of exports, 3.5M workers), agriculture, leather, telecommunications, shipbuilding, pharmaceuticals, food processing, remittances",
        "ai_risk_high": "Garment manufacturing (3.5M workers at risk), call centers, agricultural processing, basic admin, textile assembly",
        "ai_risk_medium": "Banking, telecommunications, leather manufacturing, logistics, pharmaceuticals admin",
        "ai_risk_low": "Healthcare, education, skilled trades, agriculture, pharmaceutical R&D, shipbuilding engineering",
        "key_challenges": "Garment industry AI disruption (80% of exports vulnerable), remittance dependency ($21B/year), climate change vulnerability, infrastructure gaps, labor safety",
        "references": [
            ("World Bank - Bangladesh Data", "https://data.worldbank.org/country/bangladesh"),
            ("BBS - Bangladesh Statistics", "https://www.bbs.gov.bd/"),
            ("Trading Economics - Bangladesh", "https://tradingeconomics.com/bangladesh/indicators"),
            ("Bangladesh Bank", "https://www.bangladesh-bank.org/"),
            ("ADB - Bangladesh Country Profile", "https://www.adb.org/countries/bangladesh/main"),
        ]
    },
    "russia": {
        "name": "Russia", "slug": "russia-russia", "population": "146 million",
        "gdp_per_capita": "$14,871", "gdp_per_capita_ppp": "$37,600", "gdp_growth": "3.6% (2024, driven by defense spending)",
        "currency": "RUB", "avg_monthly_salary": "RUB 104,158 (~$1,208 USD at Jan 2025 rates)",
        "avg_salary_usd": "$1,208", "minimum_wage": "RUB 19,242/month (2025)",
        "it_salary_range": "RUB 1.5M-3.5M/month; senior RUB 5M-10M+",
        "manufacturing_salary": "RUB 800,000-1.5M/month (~$9,300-17,400 USD/year)",
        "unemployment": "3.0%",
        "ai_adoption": "Developing; Yandex as Russian AI leader; government AI Strategy; sanctions impact on tech imports",
        "internet_penetration": "91%", "literacy_rate": "99%",
        "stem_graduates": "~350,000 annually",
        "labor_force": "72 million",
        "key_industries": "Oil & gas, metals, chemicals, machinery, defense, telecommunications, automotive, food processing, timber",
        "ai_risk_high": "Oil/gas admin, call centers, manufacturing assembly, basic data processing, retail",
        "ai_risk_medium": "Automotive manufacturing, banking, metals processing, logistics, defense (limited)",
        "ai_risk_low": "Healthcare, education, skilled trades, oil/gas engineering, creative industries, defense R&D",
        "key_challenges": "Western sanctions impact, currency volatility, brain drain (tech workers emigrating), defense spending burden, economic diversification needs, demographic decline",
        "references": [
            ("World Bank - Russia Data", "https://data.worldbank.org/country/russia"),
            ("Rosstat - Russian Statistics", "https://rosstat.gov.ru/"),
            ("Trading Economics - Russia", "https://tradingeconomics.com/russia/indicators"),
            ("Central Bank of Russia", "https://www.cbr.ru/"),
            ("IMF - Russia Economic Profile", "https://www.imf.org/en/Countries/RUS"),
        ]
    },
    "saudi-arabia": {
        "name": "Saudi Arabia", "slug": "saudi-arabia-saudi-arabia", "population": "36 million",
        "gdp_per_capita": "$35,231", "gdp_per_capita_ppp": "$71,700", "gdp_growth": "1.6% (2024)",
        "currency": "SAR", "avg_monthly_salary": "SAR 10,000 (~$2,665 USD; varies widely by sector/nationality)",
        "avg_salary_usd": "$2,665", "minimum_wage": "SAR 3,000/month (2023, applies to Saudi nationals)",
        "it_salary_range": "SAR 50,000-150,000/month; senior SAR 200,000-400,000+",
        "manufacturing_salary": "SAR 8,000-15,000/month (~$2,130-4,000 USD)",
        "unemployment": "6.0% (among Saudi nationals; higher youth unemployment)",
        "ai_adoption": "Strategic focus; Vision 2030 tech initiatives; government investment in AI hubs (GAQC, Aramco digital labs)",
        "internet_penetration": "96%", "literacy_rate": "97%",
        "stem_graduates": "~100,000 annually",
        "labor_force": "13 million (mostly Saudi; 1M+ expat workers)",
        "key_industries": "Oil & gas, petrochemicals, financial services, retail, telecommunications, construction, manufacturing",
        "ai_risk_high": "Oil sector admin, call centers, financial back-office, retail, basic manufacturing",
        "ai_risk_medium": "Automotive manufacturing, banking, petrochemical operations, logistics, hospitality",
        "ai_risk_low": "Healthcare, education, skilled trades, oil industry engineering, finance, tourism",
        "key_challenges": "Oil dependency (declining per-capita income), youth unemployment (32%+), Saudization challenges, renewable energy transition, expat workforce dependence",
        "references": [
            ("World Bank - Saudi Arabia Data", "https://data.worldbank.org/country/saudi-arabia"),
            ("GASTAT - Saudi Statistics", "https://www.stats.gov.sa/en/"),
            ("Trading Economics - Saudi Arabia", "https://tradingeconomics.com/saudi-arabia/indicators"),
            ("Saudi Central Bank", "https://www.sama.gov.sa/"),
            ("Vision 2030 - Saudi Tech Initiatives", "https://www.vision2030.gov.sa/"),
        ]
    },
    "uae": {
        "name": "United Arab Emirates", "slug": "uae-uae", "population": "10 million",
        "gdp_per_capita": "$50,216", "gdp_per_capita_ppp": "$84,200", "gdp_growth": "3.5% (2024)",
        "currency": "AED", "avg_monthly_salary": "AED 12,500 (~$3,400 USD; highly stratified)",
        "avg_salary_usd": "$3,400", "minimum_wage": "AED 3,000/month (2024, for limited sectors)",
        "it_salary_range": "AED 60,000-180,000/month; senior AED 200,000-400,000+",
        "manufacturing_salary": "AED 10,000-20,000/month (~$2,700-5,400 USD)",
        "unemployment": "1.8%",
        "ai_adoption": "High; Dubai tech hub; government AI strategy; Amazon, Google, Microsoft regional hubs; Islamic fintech AI leaders",
        "internet_penetration": "100%", "literacy_rate": "97%",
        "stem_graduates": "~40,000 annually",
        "labor_force": "5.8 million (80%+ expat)",
        "key_industries": "Finance, tourism, real estate, petrochemicals, telecommunications, retail, construction, logistics, aviation",
        "ai_risk_high": "Call centers (large offshore ops), retail, hospitality services, administrative services, basic customer service",
        "ai_risk_medium": "Banking, real estate operations, logistics, tourism services, retail management",
        "ai_risk_low": "Healthcare, education, skilled trades, finance engineering, creative industries, luxury services",
        "key_challenges": "Expat workforce dependency (80%), post-oil economy transition, income inequality (expat wages), brain drain prevention for nationals",
        "references": [
            ("World Bank - UAE Data", "https://data.worldbank.org/country/united-arab-emirates"),
            ("UAE Statistics Centre", "https://www.stats.gov.ae/"),
            ("Trading Economics - UAE", "https://tradingeconomics.com/united-arab-emirates/indicators"),
            ("Central Bank of UAE", "https://www.cbuae.gov.ae/"),
            ("Dubai Statistics Center", "https://www.dsc.gov.ae/"),
        ]
    },
    "singapore": {
        "name": "Singapore", "slug": "singapore-singapore", "population": "5.8 million",
        "gdp_per_capita": "$90,674", "gdp_per_capita_ppp": "$132,700", "gdp_growth": "2.4% (2024)",
        "currency": "SGD", "avg_monthly_salary": "SGD 6,138 (~$4,550 USD, including CPF)",
        "avg_salary_usd": "$4,550", "minimum_wage": "No statutory minimum; market-driven",
        "it_salary_range": "SGD 80,000-180,000/year; senior SGD 200,000-400,000+",
        "manufacturing_salary": "SGD 50,000-80,000/year (~$37,000-59,000 USD)",
        "unemployment": "2.1%",
        "ai_adoption": "Regional hub; government AI Singapore initiative; fintech, biotech AI leaders; world-class tech infrastructure",
        "internet_penetration": "99%", "literacy_rate": "97%",
        "stem_graduates": "~15,000 annually",
        "labor_force": "3.7 million (30%+ expat)",
        "key_industries": "Finance, petrochemicals, electronics, telecommunications, shipping/logistics, tourism, biotechnology, financial technology",
        "ai_risk_high": "Call centers, financial back-office, basic manufacturing, administrative services, retail",
        "ai_risk_medium": "Banking, logistics, petrochemical operations, electronics assembly, retail management",
        "ai_risk_low": "Healthcare, education, skilled trades, finance engineering, petrochemical engineering, creative industries",
        "key_challenges": "Expat workforce dependency (30%), aging population, housing affordability, regional competition (HK, Dubai), tech talent shortage",
        "references": [
            ("World Bank - Singapore Data", "https://data.worldbank.org/country/singapore"),
            ("Department of Statistics Singapore", "https://www.singstat.gov.sg/"),
            ("Trading Economics - Singapore", "https://tradingeconomics.com/singapore/indicators"),
            ("Monetary Authority of Singapore", "https://www.mas.gov.sg/"),
            ("Economic Development Board Singapore", "https://www.edb.gov.sg/"),
        ]
    },
    "taiwan": {
        "name": "Taiwan", "slug": "taiwan-taiwan", "population": "23.8 million",
        "gdp_per_capita": "$34,060", "gdp_per_capita_ppp": "$74,200", "gdp_growth": "4.2% (2024)",
        "currency": "TWD", "avg_monthly_salary": "TWD 46,450 (~$1,420 USD)",
        "avg_salary_usd": "$1,420", "minimum_wage": "TWD 28,200/month (2025)",
        "it_salary_range": "TWD 800,000-1.5M/year; senior TWD 2M-4M+",
        "manufacturing_salary": "TWD 400,000-700,000/year (~$12,200-21,400 USD)",
        "unemployment": "3.7%",
        "ai_adoption": "High; TSMC semiconductor leadership; smartphone/electronics AI chips; government digital transformation",
        "internet_penetration": "98%", "literacy_rate": "99%",
        "stem_graduates": "~80,000 annually",
        "labor_force": "12 million",
        "key_industries": "Semiconductors (TSMC), electronics, petrochemicals, machinery, textiles, financial services, telecommunications",
        "ai_risk_high": "Electronics assembly, call centers, basic manufacturing, textile production, retail",
        "ai_risk_medium": "Semiconductor manufacturing, automotive, telecommunications, logistics, financial services",
        "ai_risk_low": "Healthcare, education, skilled trades, semiconductor engineering, creative industries, finance",
        "key_challenges": "Demographic crisis (0.87 fertility rate, aging 16% over 65), brain drain, geopolitical tensions with China, cross-strait uncertainty, wage stagnation",
        "references": [
            ("World Bank - Taiwan Data", "https://data.worldbank.org/country/china-taiwan"),
            ("DGBAS - Taiwan Statistics", "https://www.stat.gov.tw/"),
            ("Trading Economics - Taiwan", "https://tradingeconomics.com/taiwan/indicators"),
            ("Central Bank of Taiwan", "https://www.cbc.gov.tw/"),
            ("National Development Council Taiwan", "https://www.ndc.gov.tw/"),
        ]
    },
    "israel": {
        "name": "Israel", "slug": "israel-israel", "population": "9.5 million",
        "gdp_per_capita": "$54,190", "gdp_per_capita_ppp": "$99,800", "gdp_growth": "2.1% (2024, war impact)",
        "currency": "ILS", "avg_monthly_salary": "ILS 16,500 (~$4,450 USD)",
        "avg_salary_usd": "$4,450", "minimum_wage": "ILS 7,470/month (2025)",
        "it_salary_range": "ILS 120,000-250,000/month; senior ILS 300,000-600,000+",
        "manufacturing_salary": "ILS 50,000-100,000/month (~$13,500-27,000 USD)",
        "unemployment": "3.9%",
        "ai_adoption": "Very high; startup nation; 2000+ AI startups; AI cybersecurity, autonomous vehicles; tech giants (Microsoft, Google, Intel) R&D hubs",
        "internet_penetration": "92%", "literacy_rate": "99%",
        "stem_graduates": "~60,000 annually",
        "labor_force": "4.3 million",
        "key_industries": "Software, semiconductors, defense technology, telecommunications, chemicals, pharmaceuticals, financial services, diamond polishing",
        "ai_risk_high": "Call centers, administrative services, basic manufacturing, data entry, retail",
        "ai_risk_medium": "Cybersecurity admin (monitoring), telecommunications, logistics, financial back-office",
        "ai_risk_low": "Healthcare, education, defense R&D (valued for security expertise), semiconductor engineering, creative industries",
        "key_challenges": "Security costs, internal political divisions, Arab-Israeli tensions, demographic gaps (ultra-Orthodox), tech sector wage inequality, religious-secular tensions",
        "references": [
            ("World Bank - Israel Data", "https://data.worldbank.org/country/israel"),
            ("Central Bureau of Statistics Israel", "https://www.cbs.gov.il/"),
            ("Trading Economics - Israel", "https://tradingeconomics.com/israel/indicators"),
            ("Bank of Israel", "https://www.boi.org.il/"),
            ("Israel Innovation Authority", "https://innovationisrael.org.il/"),
        ]
    },
    "ireland": {
        "name": "Ireland", "slug": "ireland-ireland", "population": "5.3 million",
        "gdp_per_capita": "$91,514", "gdp_per_capita_ppp": "$125,600", "gdp_growth": "2.0% (2024)",
        "currency": "EUR", "avg_monthly_salary": "€4,443 (~$4,900 USD)",
        "avg_salary_usd": "$4,900", "minimum_wage": "€14.00/hour (2025)",
        "it_salary_range": "€70,000-140,000/year; senior €150,000-300,000+",
        "manufacturing_salary": "€40,000-70,000/year",
        "unemployment": "4.3%",
        "ai_adoption": "Strong; EU AI hub; major tech giants (Google, Facebook, Microsoft) EMEA HQs; fintech and biotech AI",
        "internet_penetration": "96%", "literacy_rate": "99%",
        "stem_graduates": "~40,000 annually",
        "labor_force": "2.6 million",
        "key_industries": "Pharmaceuticals, technology, financial services, food & beverage, telecommunications, chemicals, manufacturing, tourism",
        "ai_risk_high": "Administrative services, call centers, financial back-office, data entry, basic customer service",
        "ai_risk_medium": "Banking, manufacturing, insurance, logistics, telecommunications operations",
        "ai_risk_low": "Healthcare, education, skilled trades, pharmaceutical R&D, finance engineering, creative industries",
        "key_challenges": "Housing affordability crisis, healthcare system strain, brain drain (Dublin-focused), inequality, post-pandemic inflation, EU compliance burden",
        "references": [
            ("World Bank - Ireland Data", "https://data.worldbank.org/country/ireland"),
            ("CSO - Central Statistics Office", "https://www.cso.ie/"),
            ("Trading Economics - Ireland", "https://tradingeconomics.com/ireland/indicators"),
            ("Central Bank of Ireland", "https://www.centralbank.ie/"),
            ("OECD - Ireland Economic Survey", "https://www.oecd.org/en/topics/sub-issues/economic-surveys-ireland.html"),
        ]
    },
    "netherlands": {
        "name": "Netherlands", "slug": "netherlands-netherlands", "population": "17.7 million",
        "gdp_per_capita": "$67,690", "gdp_per_capita_ppp": "$87,400", "gdp_growth": "1.2% (2024)",
        "currency": "EUR", "avg_monthly_salary": "€3,875 (~$4,275 USD)",
        "avg_salary_usd": "$4,275", "minimum_wage": "€15.45/hour (2025)",
        "it_salary_range": "€65,000-120,000/year; senior €130,000-250,000+",
        "manufacturing_salary": "€40,000-70,000/year",
        "unemployment": "3.9%",
        "ai_adoption": "Strong; Amsterdam AI research hub; fintech innovation; EU AI Act leadership",
        "internet_penetration": "98%", "literacy_rate": "99%",
        "stem_graduates": "~90,000 annually",
        "labor_force": "9.3 million",
        "key_industries": "Financial services, chemicals, oil refining, food & beverage, automotive, telecommunications, agriculture, energy",
        "ai_risk_high": "Administrative services, call centers, financial back-office, data entry, basic customer service",
        "ai_risk_medium": "Banking, logistics, manufacturing, insurance, telecommunications",
        "ai_risk_low": "Healthcare, education, skilled trades, chemical engineering, agriculture, creative industries",
        "key_challenges": "Cost of living crisis, housing shortage, immigration tensions, aging population, nitrogen pollution disputes, skill gaps",
        "references": [
            ("World Bank - Netherlands Data", "https://data.worldbank.org/country/netherlands"),
            ("CBS - Statistics Netherlands", "https://www.cbs.nl/"),
            ("Trading Economics - Netherlands", "https://tradingeconomics.com/netherlands/indicators"),
            ("Dutch Central Bank", "https://www.dnb.nl/"),
            ("OECD - Netherlands Economic Survey", "https://www.oecd.org/en/topics/sub-issues/economic-surveys-netherlands.html"),
        ]
    },
    "sweden": {
        "name": "Sweden", "slug": "sweden-sweden", "population": "10.7 million",
        "gdp_per_capita": "$57,213", "gdp_per_capita_ppp": "$83,500", "gdp_growth": "2.6% (2024)",
        "currency": "SEK", "avg_monthly_salary": "SEK 34,800 (~$3,150 USD; gross)",
        "avg_salary_usd": "$3,150", "minimum_wage": "No statutory minimum; union-negotiated (~SEK 180-200/hour)",
        "it_salary_range": "SEK 600,000-1.2M/year; senior SEK 1.5M-3M+",
        "manufacturing_salary": "SEK 350,000-550,000/year",
        "unemployment": "7.2% (rising)",
        "ai_adoption": "High; Spotify, King Digital, iZettle as AI-driven companies; strong R&D ecosystem",
        "internet_penetration": "97%", "literacy_rate": "99%",
        "stem_graduates": "~50,000 annually",
        "labor_force": "5.2 million",
        "key_industries": "Automotive (Volvo, Scania), telecommunications, machinery, chemicals, pharmaceuticals, forestry, financial services, music/gaming",
        "ai_risk_high": "Administrative services, call centers, basic manufacturing, customer service, data entry",
        "ai_risk_medium": "Automotive manufacturing, telecommunications, banking, logistics, forestry operations",
        "ai_risk_low": "Healthcare, education, skilled trades, automotive engineering, R&D, creative industries (gaming/music)",
        "key_challenges": "Immigration integration tensions, rising unemployment (7.2%), public sector reform needs, healthcare pressure, energy prices (post-Russian cuts)",
        "references": [
            ("World Bank - Sweden Data", "https://data.worldbank.org/country/sweden"),
            ("SCB - Statistics Sweden", "https://www.scb.se/"),
            ("Trading Economics - Sweden", "https://tradingeconomics.com/sweden/indicators"),
            ("Riksbank - Central Bank Sweden", "https://www.riksbank.se/"),
            ("OECD - Sweden Economic Survey", "https://www.oecd.org/en/topics/sub-issues/economic-surveys-sweden.html"),
        ]
    },
    "sri-lanka": {
        "name": "Sri Lanka", "slug": "sri-lanka-srilanka", "population": "22.2 million",
        "gdp_per_capita": "$4,516", "gdp_per_capita_ppp": "$13,200", "gdp_growth": "5.5% (2024, recovery)",
        "currency": "LKR", "avg_monthly_salary": "LKR 80,000-120,000 (~$240-360 USD)",
        "avg_salary_usd": "$240-360", "minimum_wage": "LKR 18,150/month (2024, textile workers)",
        "it_salary_range": "LKR 1.5M-4M/year (~$4,500-12,000 USD); senior LKR 6M-12M+",
        "manufacturing_salary": "LKR 500,000-1M/year (~$1,500-3,000 USD)",
        "unemployment": "4.1%",
        "ai_adoption": "Emerging; tech outsourcing hub for India/US; fintech growth; government digital transformation post-crisis",
        "internet_penetration": "57%", "literacy_rate": "92%",
        "stem_graduates": "~50,000 annually",
        "labor_force": "10 million",
        "key_industries": "Apparel (50% of exports), tea, rubber, tourism, telecommunications, financial services, food processing, agriculture",
        "ai_risk_high": "Apparel manufacturing, call centers, tea processing, agricultural admin, basic manufacturing",
        "ai_risk_medium": "Apparel operations, banking, telecommunications, tourism operations, logistics",
        "ai_risk_low": "Healthcare, education, skilled trades, tourism management, agriculture, creative industries",
        "key_challenges": "2022 economic crisis aftermath, currency volatility (LKR depreciation), debt distress, unemployment from IMF austerity, apparel industry pressure, tourism recovery",
        "references": [
            ("World Bank - Sri Lanka Data", "https://data.worldbank.org/country/sri-lanka"),
            ("Department of Census Statistics Sri Lanka", "https://www.statistics.gov.lk/"),
            ("Trading Economics - Sri Lanka", "https://tradingeconomics.com/sri-lanka/indicators"),
            ("Central Bank of Sri Lanka", "https://www.cbsl.gov.lk/"),
            ("ADB - Sri Lanka Country Profile", "https://www.adb.org/countries/sri-lanka/main"),
        ]
    },
}


def rewrite_country(key):
    c = COUNTRIES[key]
    slug = c["slug"]
    count = 0
    # Always write to canonical path — no fuzzy matching
    for aud in AUDIENCES:
        fn = os.path.join(ARTICLES_DIR, f"countries-{slug}-{aud}-edition.html")
        with open(fn, 'w', encoding='utf-8') as f:
            f.write(gen_article(c, aud, fn))
        count += 1
    print(f"  ✓ {c['name']}: {count} articles")
    return count


def main():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    total = 0
    for key in COUNTRIES:
        total += rewrite_country(key)
    print(f"\nDone! {total} articles rewritten.")

if __name__ == "__main__":
    main()
